#规划GateWay的服务端口
server:
  port: 8888
#规划gateWay注册到到nacos上的服务应用名称
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        #gateway工程注册到nacos上的地址
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          #开启gateway从nacos上获取服务列表
          enabled: true
#  profiles:
#    active: allFilter

#开启acutor端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      #打开端点详情
      show‐details: always
