server:
  port: 9999
spring:
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    username: alibaba
    password: alibabaPwd
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.231.85.51:3306/sso?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 127.0.0.1
    port: 6379
